### ISSUE TITLE
The request fails

### ISSUE THREAD

**Issue by craftbyte** [pebble-examples/hello-timeline#1]
Log: [INFO    ] I ocess_manager.c:368 Heap Usage for App <hello-time: Total Size <64360B> Used <740B> Still allocated <0B>
[INFO    ] Error getting timeline token: Internal failure.

**Comment by matthewtole** [comment]
Could you try it again now? We had a small amount of downtime early today in the timeline infrastructure that might have cause your error.

**Comment by amamut** [comment]
I'm getting an error which seems to be related:
Error getting timeline token: No token available for this app and user.

**Comment by craftbyte** [comment]
@matthewtole No, it wasn't that.
![](https://i.imgur.com/U0bX1ML.png)
![](https://i.imgur.com/W3VidfP.png)
![](https://i.imgur.com/drpmK19.png)

**Comment by matthewtole** [comment]
@amamut Your error is probably because you haven't registered your app on the Pebble Developer Portal. We're going to update the README on this example to make it more explicit, but for now you can check out our guide: https://developer.getpebble.com/guides/timeline/timeline-enabling/

@craftbyte I am looking into your error.

**Comment by matthewtole** [comment]
@craftbyte Could you try running the emulator in debug mode so I can see the log messages? You will need to kill the emulator and then run:

```
pebble install --debug --logs
```

**Comment by craftbyte** [comment]
@matthewtole 

```
/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
Traceback (most recent call last):
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/Pebble/common/phonesim/javascript/pebble.py", line 224, in go
    token = self._get_timeline_token()
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/Pebble/common/phonesim/javascript/pebble.py", line 213, in _get_timeline_token
    headers={'Authorization': 'Bearer %s' % self.runtime.runner.oauth_token})
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
    self._validate_conn(conn)
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
    conn.connect()
  File "/Users/anze/pebble-dev/PebbleSDK-3.0-dp4/.env/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 253, in connect
    match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 245, in match_hostname
    raise ValueError("empty or no certificate, match_hostname needs a "
ValueError: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```

**Comment by matthewtole** [comment]
@craftbyte There's currently an issue using Python 2.7.8+ with the timeline API. You can either downgrade your Python installation (you should be able to do `brew uninstall python`) or you can use our amazing online IDE, [CloudPebble](https://cloudpebble.net), to work with the timeline API.

**Comment by craftbyte** [comment]
@matthewtole when can we expect a fix?

**Comment by mfollett** [comment]
@matthewtole if we use CloudPebble do we then need to find some place where we can run the node app exposed to the internet, or will CloudPebble also run that somehow?

**Comment by matthewtole** [comment]
@mfollett Yes. You will need to host the app somewhere if you want to use CloudPebble. I recommend Heroku, you can create an app for free!
